# Generated by Django 6.0.3 on 2026-03-29 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_flashcard_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='topic',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='alg_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.algset'),
        ),
    ]
