# Generated by Django 6.0.3 on 2026-03-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_algset_remove_flashcard_topic_flashcard_alg_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='algset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='set_images/'),
        ),
    ]
