# Generated by Django 6.0.3 on 2026-03-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_algset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='name',
            field=models.CharField(default='Unnamed Case', max_length=100),
        ),
    ]
