# Generated by Django 6.0.3 on 2026-03-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_flashcard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='status',
            field=models.IntegerField(choices=[(1, 'Learning'), (2, 'Unlearnt'), (3, 'Learnt')], default=2),
        ),
    ]
